# Generated by Django 5.2.1 on 2025-05-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_skill_proficiency_education_relevant_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='relevant_courses',
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RelevantCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevant_courses', to='resume.education')),
            ],
            options={
                'verbose_name_plural': 'Relevant Courses',
                'ordering': ['course_name'],
            },
        ),
    ]
