# Generated by Django 5.2.1 on 2025-05-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_education_relevant_courses_education_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevantcourse',
            name='description',
        ),
    ]
