# Generated by Django 5.2.1 on 2025-05-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_contactinfo_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='last_name',
        ),
    ]
