# Generated by Django 5.2.1 on 2025-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_experience_is_current_experience_skills_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='projectsection',
            name='description',
        ),
        migrations.AlterField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'tech'}, related_name='experiences', to='resume.skill'),
        ),
    ]
