# Generated by Django 5.2.1 on 2025-05-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='education',
            name='relevant_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
