# Generated by Django 5.2.1 on 2025-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_relevantcourse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('tech', 'Technical Skills'), ('soft', 'Soft Skills')], default='lang', max_length=20),
        ),
    ]
