# Generated by Django 5.2.1 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_technology_description'),
        ('resume', '0005_language_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Projects', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(related_name='resume_sections', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Sections',
            },
        ),
    ]
