# Generated by Django 5.2.1 on 2025-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_contactinfo_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='resume.skill'),
        ),
    ]
