# Generated by Django 5.2.1 on 2025-05-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_hobby_remove_projectsection_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-proficiency', 'name'], 'verbose_name_plural': 'Languages'},
        ),
    ]
