# Generated by Django 5.2.1 on 2025-06-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_image',
        ),
    ]
