services:
  - type: web
    name: portfolio-app
    env: python
    buildCommand: |
      npm install
      npm run build
      python manage.py collectstatic --noinput
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_app.settings
      - key: PYTHON_VERSION
        value: 3.11