# Generated by Django 5.2.1 on 2025-05-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
    ]
